---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false # roles use ansible_os_family env vars
  vars_files:
    - group_vars/vars.yml
#    - group_vars/vault.yml
#    - vars/main.yml  

  roles:
    - { role: setup }
    - { role: java }
    - { role: tomcat }
    - { role: postgresql }
    - { role: xnat }
      

